config/routes.rb
Rails.application.routes.draw do
  # resources :note_tags
  # resources :tags

  devise_for :users, controllers: {
       sessions: 'users/sessions',
       registrations: 'users/registrations',
       passwords: 'users/passwords'
     }

  resources :notes do
    member do
      post 'share'
      post 'add_tags'
      delete 'remove_tag/:tag_id', action: "remove_tag", as: :remove_tag
      delete 'remove_user/:user_id', action: "remove_user", as: :remove_user
    end
    get 'edit_permission/:note_user_id', action: "edit_permission", as: :edit_permission, on: :collection
    patch 'save_permission/:note_user_id', action: "save_permission", as: :save_permission, on: :collection
  end

  root 'notes#index'
end

app/models/note.rb
class Note < ApplicationRecord
  enum status: [:active, :deleted]

  # Associations
  belongs_to :created_by, class_name: "User", foreign_key: "created_by_id"

  has_many :note_users, dependent: :destroy
  has_many :users, through: :note_users
  has_many :note_tags, dependent: :destroy
  has_many :tags, through: :note_tags

  # Validations
  validates :body, presence: true

  def formatted_title
    self.body[0..10]
  end

  def all_tags
    self.tags.map(&:name).join(",")
  end

  def all_users_without_this_note
    user_ids = self.users.pluck(:id)
    user_ids << self.created_by_id
    @users = User.where.not(id: user_ids)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  before_action :check_request_type, except: [:index] #Except for index, if request type is html, redirect to root_path. Block HTML request throughout

  before_action :set_note, only: [:show, :edit, :update, :destroy, :share, :add_tags, :remove_tag, :remove_user]

  before_action :note_permission, only: [:show, :edit, :update, :destroy, :share, :add_tags]

  before_action :set_note_user, only: [:edit_permission, :save_permission] # Find user note for permission changing

  def index
     if user_signed_in?
      get_created_and_shared_notes
      @note = current_user.created_notes.new
    else
      redirect_to user_session_path
    end
  end

  def show
    get_users
    # @users = User.where.not(id: [current_user.id, @note.created_by.id])
  end

  def new
    @note = current_user.created_notes.new
  end

  def edit
    redirect_to notes_path unless @permissions.has_key?("2")
  end

  def create
    @note = current_user.created_notes.new(note_params)
    if @note.save
      @created_notes = current_user.created_notes.all
      note_permission
      get_users
    end
    respond_to do |format|
      format.js
    end
  end

  def update
    @note.update(note_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @note.destroy
      get_created_and_shared_notes
      @note = current_user.created_notes.new
    end
    respond_to do |format|
      format.js
    end
  end

  def share
    unless @permissions.has_key?("3")
      @error = "You're not allowed to perform this action"
    end
    user_ids = params[:user][:ids].reject { |p| p.empty? } if params[:user][:ids].present?
    permission_ids = params[:permission][:ids].reject { |p| p.empty? } if params[:permission][:ids].present?
    if user_ids.empty?
      @error = "Please select users to share notes"
    elsif permission_ids.empty?
      @error = "Please select atleast one permission"
    else
      permission_hash = {}
      permission_ids.map {|p| permission_hash["#{p}"] = true}
      user_ids.map do |user_id|
        n = current_user.shared_notes.new(user_id: user_id, note: @note, permissions: permission_hash )
        n.save
      end
      get_users
      @success = "Note shared successfully!"
    end
    respond_to do |format|
      format.js { render :file => "notes/all_users.js.erb" }
    end
  end

  def add_tags
    tags = params[:tags].split(",").reject { |tag| tag.empty? } if params[:tags].present?

    if tags.nil? || tags.empty?
      @error = "Please add a tag"
    else
      tags.map do |tag|
        @existing_tag = Tag.find_or_create_by(name: tag.downcase.strip)
        tag = @note.note_tags.new(added_by: current_user, tag: @existing_tag)
        tag.save
        @count = @note.note_tags.count
      end
      @success = "Tags added successfully!"
    end
    respond_to do |format|
      format.js { render :file => "notes/all_tags.js.erb" }
    end
  end

  def remove_tag
    tag = @note.note_tags.find_by(tag_id: params[:tag_id])
    if tag.present? &&  tag.destroy
      @success = "Tag destroyed successfully!"
      @count = @note.note_tags.count
    else
      @error = "There seems to be an issue. Please select the note and try again"
    end
    respond_to do |format|
        format.js { render :file => "notes/all_tags.js.erb" }
    end
  end

  def remove_user
    note = @note.note_users.find_by(user_id: params[:user_id])
    if note.present? && note.destroy
      get_users
      @success = "All permissions revoked from this user successfully!"
    else
      @error = "There seems to be an issue. Please try again"
    end
    # @users = User.where.not(id: [current_user.id, @note.created_by.id])
    respond_to do |format|
        format.js { render :file => "notes/all_users.js.erb" }
    end
  end

  def edit_permission
    @permissions = Permission.all.order(:id)
  end

  def save_permission
    permission_ids = params[:permissions].reject { |p| p.empty? } if params[:permissions].present?
    if permission_ids.empty?
      @error = "Please select atleast one permission"
    else
      permission_hash = {}
      permission_ids.map {|p| permission_hash["#{p}"] = true}

       if @note_user.update(permissions: permission_hash)
         @note = @note_user.note
         get_users
         @success = "Permissions changed successfully!"
       else
         @error = "The permission couldn't be saved. Please try again"
       end
    end

    respond_to do |format|
        format.js { render :file => "notes/all_users.js.erb" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.created_notes.find_by(id: params[:id])
      @note = current_user.notes.find_by(id: params[:id]) unless @note
      if @note.nil?
        respond_to do |format|
          format.js { render :file => "layouts/shared/error.js.erb" }
        end
      end
    end

    def set_note_user
      @note_user = NoteUser.find(params[:note_user_id])
    end

    def note_permission
      if @note.created_by == current_user
        @permissions = ActiveSupport::HashWithIndifferentAccess.new("1": "true", "2": "true", "3": "true")
      else
        @permissions = @note.note_users.find_by(user: current_user).permissions.with_indifferent_access
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:body, :title)
    end

    def get_users
      # @users = User.where.not(id: [current_user.id, @note.created_by.id])
      @users = @note.all_users_without_this_note
    end

    def check_request_type
      redirect_to root_path if request.format.html?
    end

    def get_created_and_shared_notes
      @created_notes = current_user.created_notes.all.order(updated_at: :desc)
      @shared_with_notes = current_user.note_users.all.order(updated_at: :desc)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
  def formatted_body(note)
    truncate(note.body, length: 40)
  end
end

app/views/notes/_edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/_edit_permission.html.erb
<div class="modal-header">
  <h5 class="modal-title">Change Permissions for <strong><%= @note_user.user.email %></strong> </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<%= form_tag save_permission_notes_path(@note_user), method: :patch, remote: true do %>
  <div class="modal-body text-center">
    <div class="btn-group" data-toggle="buttons">
      <% @permissions.each do |permission| %>
        <% active_class = @note_user.permissions["#{permission.id}"] == "true" ? true : false %>
        <%= render partial: 'permission', locals: {active_class: active_class, permission: permission} %>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <%= submit_tag "Update Permissions", class: "btn btn-success" %>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/notes/_notes.html.erb
<ul class="list">
  <% notes.each do |note| %>
      <%= render partial: 'note', locals: { note: note } %>
  <% end %>
</ul>

app/views/notes/_permission.html.erb
<%= hidden_field_tag 'permissions[]', nil %>
<% if active_class %>
  <label class='btn btn-primary btn-lg active'>
    <%= check_box_tag 'permissions[]', permission.id, true %>
    <%= permission.name.titleize %>
  </label>
<% else %>
  <label class='btn btn-primary btn-lg'>
    <%= check_box_tag 'permissions[]', permission.id %>
    <%= permission.name.titleize %>
  </label>
<% end %>

app/views/notes/_shared_notes.html.erb
<ul class="list">
  <% @shared_with_notes.each do |user_note| %>
    <% note = user_note.note %>
    <%= render partial: 'note', locals: { note: note } %>
  <% end %>
</ul>

app/views/notes/_show.html.erb
<% if @permissions.has_key?("2") || @permissions.has_key?("3") %>
 <a href="javascript:void(0)" class="pull-right fab-button btn btn-danger"><span onclick="openNav()">Actions</span></a>
<% end %>

<% if (@permissions.has_key?("1") && @permissions.has_key?("2")) || @permissions.has_key?("3") %>
  <textarea class="paper edit-note" data-note-id="<%= @note.id %>"><%= @note.body %></textarea>
<% elsif @permissions.has_key?("1") %>
  <textarea class="paper" data-note-id="<%= @note.id %>"><%= @note.body %></textarea>
<% else %>
  <div class="no-notes">
    <h4>You do not have the permission to view this note.</h4>
  </div>
<% end %>

<div id="mySidenav" class="sidenav">
  <div style="padding:0 20px">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <div>
      <% if @permissions == {} %>
        Not enoungh permissions
      <% else %>
        <% if @permissions.has_key?("3") %>
          <div class="all-users">
            <%= render partial: 'user' %>
          </div>

          <div class="all-tags">
            <%= render partial: 'tag' %>
          </div>

          <div class="delete-note">
            <%= link_to "Delete Note", note_path(@note), method: :delete, remote: true, class: "btn btn-danger btn-lg" %>
          </div>
        <% elsif @permissions.has_key?("2") %>
          <div class="all-tags">
            <%= render partial: 'tag' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(".share-notes" ).select2({'width': '100%',
                              'placeholder': "Select the users",
                              'allowClear': true});
  $(".notes-permissions" ).select2({'width': '100%',
                              'placeholder': "Select the permissions",
                              'allowClear': true});

  var note_body = $('textarea.paper.edit-note').val();
  setInterval(function(){ autoSaveNote(note_body); }, 10000);

</script>

app/views/notes/all_tags.js.erb
<% if @error %>
  toastr.error('<%= @error %>')
<% else %>
  toastr.success('<%= @success %>')

  $('.all-tags').html("<%=j render partial: 'tag' %>");
  <% if @count %>
    $('span[data-note-id=<%= @note.id %>]').html("<%= @count %>");
  <% end %>
<% end %>

app/views/notes/all_users.js.erb
<% if @error %>
  toastr.error('<%= @error %>')
<% else %>
  toastr.success('<%= @success %>')

  $('.all-users').html("<%=j render partial: 'user' %>")

  $(".share-notes" ).select2({'width': '100%',
                              'placeholder': "Select the users",
                              'allowClear': true});
  $(".notes-permissions" ).select2({'width': '100%',
                              'placeholder': "Select the permissions",
                              'allowClear': true});

  var note_body = $('textarea.paper.edit-note').val();
  setInterval(function(){ autoSaveNote(note_body); }, 10000);

  $('#editNoteUserPermissions').modal('hide');
<% end %>

app/views/notes/create.js.erb
<% if @note.errors.any? %>
  <% @note.errors.full_messages.each do |message| %>
    toastr.error('<%= message %>')
  <% end %>
<% else %>
  toastr.success("Note saved!")
  $('#my-notes').html('<%=j render partial: "notes", locals: {notes: @created_notes} %>');
  $('.note-container').html('<%=j render partial: "show" %>')
<% end %>

app/views/notes/edit.js.erb
$('#note_container').html('<%=j render partial: "edit" %>')

app/views/notes/index.html.erb
<%= content_for :body_class, "notes" %>
<div class="container">
  <div class="row">

    <div class="col-sm-4 no-gutter-right">
      <div class="notes-container">

        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#my-notes" aria-controls="my-notes" role="tab" data-toggle="tab">My Notes</a>
          </li>
          <li role="presentation">
            <a href="#shared-notes" aria-controls="shared-notes" role="tab" data-toggle="tab">Shared Notes</a>
          </li>
          <li role="presentation" class="pull-right">
            <%= link_to new_note_path, remote: true, class: "new" do %>
              <img src="https://image.flaticon.com/icons/png/512/148/148764.png" width="14" alt="">
            New
            <% end %>
          </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="my-notes">
            <%= render partial: "notes", locals: { notes: @created_notes } %>
          </div>
          <div role="tabpanel" class="tab-pane" id="shared-notes">
            <%= render partial: "shared_notes", locals: { notes: @shared_with_notes } %>
          </div>
        </div>

      </div>
    </div>
    <div class="col-sm-8 no-gutter-left">
      <div class="note-container" id="note_container">
        <%= render partial: "new" %>
      </div>

      <div class="modal fade" id="editNoteUserPermissions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
          </div>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/notes/new.js.erb
$('#note_container').html('<%=j render partial: "new" %>')

app/views/notes/save_permission.js.erb
$('#editNoteUserPermissions').modal('hide');

app/views/notes/show.js.erb
$('.note-container').html('<%=j render partial: "show" %>')
$('ul.list li').removeClass('active');
$("ul.list li[data-note-id= <%= @note.id %>]").addClass('active');