config/routes.rb
Rails.application.routes.draw do
  # resources :note_tags
  # resources :tags

  devise_for :users, controllers: {
       sessions: 'users/sessions',
       registrations: 'users/registrations',
       passwords: 'users/passwords'
     }

  resources :notes do
    member do
      post 'share'
      post 'add_tags'
      delete 'remove_tag/:tag_id', action: "remove_tag", as: :remove_tag
      delete 'remove_user/:user_id', action: "remove_user", as: :remove_user
    end
    get 'edit_permission/:note_user_id', action: "edit_permission", as: :edit_permission, on: :collection
    patch 'save_permission/:note_user_id', action: "save_permission", as: :save_permission, on: :collection
  end

  root 'notes#index'
end

app/models/note_tag.rb
class NoteTag < ApplicationRecord

  # Associations
  belongs_to :note
  belongs_to :tag
  belongs_to :added_by, class_name: "User", foreign_key: "added_by_id"

  # Validations
  validates_uniqueness_of :note_id, :scope => :tag_id
end

app/controllers/note_tags_controller.rb
class NoteTagsController < ApplicationController
  before_action :set_note_tag, only: [:show, :edit, :update, :destroy]

  # GET /note_tags
  # GET /note_tags.json
  def index
    @note_tags = NoteTag.all
  end

  # GET /note_tags/1
  # GET /note_tags/1.json
  def show
  end

  # GET /note_tags/new
  def new
    @note_tag = NoteTag.new
  end

  # GET /note_tags/1/edit
  def edit
  end

  # POST /note_tags
  # POST /note_tags.json
  def create
    @note_tag = NoteTag.new(note_tag_params)

    respond_to do |format|
      if @note_tag.save
        format.html { redirect_to @note_tag, notice: 'Note tag was successfully created.' }
        format.json { render :show, status: :created, location: @note_tag }
      else
        format.html { render :new }
        format.json { render json: @note_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /note_tags/1
  # PATCH/PUT /note_tags/1.json
  def update
    respond_to do |format|
      if @note_tag.update(note_tag_params)
        format.html { redirect_to @note_tag, notice: 'Note tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @note_tag }
      else
        format.html { render :edit }
        format.json { render json: @note_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /note_tags/1
  # DELETE /note_tags/1.json
  def destroy
    @note_tag.destroy
    respond_to do |format|
      format.html { redirect_to note_tags_url, notice: 'Note tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note_tag
      @note_tag = NoteTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_tag_params
      params.require(:note_tag).permit(:note_id, :tag_id, :added_by_id)
    end
end

app/views/note_tags/_form.html.erb
<%= form_for(note_tag) do |f| %>
  <% if note_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note_tag.errors.count, "error") %> prohibited this note_tag from being saved:</h2>

      <ul>
      <% note_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note_id %>
    <%= f.text_field :note_id %>
  </div>

  <div class="field">
    <%= f.label :tag_id %>
    <%= f.text_field :tag_id %>
  </div>

  <div class="field">
    <%= f.label :added_by_id %>
    <%= f.text_field :added_by_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/note_tags/edit.html.erb
<h1>Editing Note Tag</h1>

<%= render 'form', note_tag: @note_tag %>

<%= link_to 'Show', @note_tag %> |
<%= link_to 'Back', note_tags_path %>

app/views/note_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Note Tags</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Tag</th>
      <th>Added by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @note_tags.each do |note_tag| %>
      <tr>
        <td><%= note_tag.note %></td>
        <td><%= note_tag.tag %></td>
        <td><%= note_tag.added_by %></td>
        <td><%= link_to 'Show', note_tag %></td>
        <td><%= link_to 'Edit', edit_note_tag_path(note_tag) %></td>
        <td><%= link_to 'Destroy', note_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note Tag', new_note_tag_path %>

app/views/note_tags/new.html.erb
<h1>New Note Tag</h1>

<%= render 'form', note_tag: @note_tag %>

<%= link_to 'Back', note_tags_path %>

app/views/note_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @note_tag.note %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @note_tag.tag %>
</p>

<p>
  <strong>Added by:</strong>
  <%= @note_tag.added_by %>
</p>

<%= link_to 'Edit', edit_note_tag_path(@note_tag) %> |
<%= link_to 'Back', note_tags_path %>